### ISSUE TITLE
Please clarify license

### ISSUE THREAD

**Issue by onlyjob** [hlandau/svcutils#1]
[MIT](https://opensource.org/licenses/mit-license.php) license [is ambiguous](https://en.wikipedia.org/wiki/MIT_License#Various_versions) (there are [too many licenses](https://fedoraproject.org/wiki/Licensing:MIT) known as _MIT_) and recommended to refer to as [Expat](https://directory.fsf.org/wiki/License:Expat).

As very minimum proper licensing should include URL to canonical text of the license or better (to avoid any doubts) commit full text of the license to `LICENSE` file.

I could not find links or text of the license anywhere in this repository...

**Comment by hlandau** [comment]
Licencing information is maintained in Git.
https://github.com/hlandau/svcutils/commit/09c5458e23bda3b8e4d925fd587bd44fbdb5950e
https://github.com/hlandau/acme/blob/master/_doc/COPYING.MIT

**Comment by onlyjob** [comment]
Hold on, this issue is not solved as licensing documentation is insufficient in this repository.
For example when software is introduced to [Debian](http://debian.org) it should be distributed with comprehensive licensing information and copyright. When this repository is cloned there is no text of the license and unlike _Apache-2.0_ or _GPL-3+_ licenses, "MIT" is not a reliable license identifier.

Commit message is a wrong place to document license: tarball export do not preserve this information and the full text of the license is also missing. Finally how do you suppose one can guess the license from SHA256 digest???

Please commit full text of the license to `LICENSE` file or modify license grant in README to include well known URL of the license like 

  https://opensource.org/licenses/mit-license.php

or 

  https://directory.fsf.org/wiki/License:Expat

Thanks.

**Comment by hlandau** [comment]
The licence is identified by a SHA256 hash of the licence text on every commit, except for commits before this practice were introduced, which are covered by a grandfathering declaration on the commit in which this practice was introduced.

**Comment by hlandau** [comment]
The purpose of the declaration is to be legally unambiguous. The location of the declaration is irrelevant, only that it is unambiguous and published. I could, hypothetically, write a statement "I hereby licence every piece of software I have ever written ever under the following terms: ..., signed Hugo Landau, witnessed" in Swahili and post it on a noticeboard in Nepal, and this would be a valid exhibit in a court of law. The grant of licence exists regardless of whether or not you are aware of it, and "proximity" is not necessary any more than a last will and testament needs to be left next to the physical assets which it governs.

**Comment by hlandau** [comment]
Adding a LICENCE file is pointless. It is highly ambiguous. The argument is that placing a file called LICENCE next to a bunch of source code files constitutes licencing those files under that LICENCE. This may convince many courts of law, but it seems to be highly ambiguous. Moreover, if I add that file now, what happens to previous versions? Are they also covered? Code that is present in both current and previous versions might be covered, but what about code in old versions that has subsequently been removed? Etc. etc.

I don't care what's the common practice; I care about what actually makes sense and what's the most unambiguous with regard to copyright law. Accordingly, I've concluded that the right place for this information is in Git, not the file tree.

**Comment by onlyjob** [comment]
Just please follow the established practice. Suppose one got tarball of _svcutils_ exported from GitHub and there is nothing whatsoever in the tarball to document the license.
Because of that I'm reluctant to introduce your work to Debian. And frankly I have too little time to convince you to do the right thing... :(

You may reduce ambiguity by adding statement whether license cover earlier commits before introduction of the license. Though I suppose most users would be interested in newer versions only...

Could you just help and at least add URL of the license to license grant? "MIT" is just not good enough. Seriously. URL of the license is a better identificator of the license than "MIT".
It would be really helpful if you could do that.

**Comment by hlandau** [comment]
The license is not identified by the letters 'MIT', it's identified by the SHA256 hashes included in commits. I can add a link to the README, I suppose.

**Comment by hlandau** [comment]
https://github.com/hlandau/svcutils#licence

**Comment by onlyjob** [comment]
That does it, thank you very much. :)

**Comment by onlyjob** [comment]
FYI @petercolberg
