### ISSUE TITLE
Please include copy of license text

### ISSUE THREAD

**Issue by petercolberg** [hlandau/svcutils#2]
Debian requires that the source package contains a copy of the license text (@onlyjob).

Thanks!

**Comment by petercolberg** [comment]
It would nice if you could tag a new release afterwards.

**Comment by petercolberg** [comment]
Commit b2b1c445a7c8c037272e3286342c9501d82c2de1 added a link to the license file, which is now [dead](https://raw.githubusercontent.com/hlandau/acme/master/_doc/COPYING.MIT) due to changes in the target repository. You have demonstrated why distributions would like a copy of the license file accompanying the source.

**Comment by hlandau** [comment]
Fixed.

You can use [relip](https://github.com/hlandau/rilts/tree/master/relip) to obtain proof-of-licence.
